// Sample data for the demo: ~90 days of a kopitiam, generated by simulating
// the business day by day. Deliveries arrive on a fixed "habit" order, usage
// follows weekday/holiday patterns, stock is used earliest-expiry first, and
// anything left when a lot expires is logged as waste. Deterministic (seeded),
// relative to today's date. generateSampleData() runs it in memory (also used
// by the pitch backtests); importSampleData() writes it to the database.

import type { PrismaClient } from "@prisma/client";
import { addDays, dayOfWeek, parseDay, todayKey } from "./dates";
import { demandMultiplier } from "./calendar";
import { BSF_PARTNER_FARM, BSF_PICKUP_THRESHOLD_KG, isBsfEligible, type Reason } from "./config";
import { mulberry32 } from "./forecast/uncertainty";

export const SAMPLE_DAYS = 90;

// Sun..Sat demand shape for a neighbourhood kopitiam (weekend breakfast peak).
const DOW = [1.25, 0.9, 0.95, 1.0, 1.0, 1.1, 1.3];
const DOW_MEAN = DOW.reduce((a, b) => a + b) / 7;

type Spec = {
  name: string;
  unit: string;
  category: string;
  unitCost: number;
  shelfLifeDays: number;
  baseDaily: number;
  orderEveryDays: number;
  overOrder: number; // habit: how much more than real demand they buy
  packSize: number;
  kgPerUnit?: number;
  trimRate?: number; // share of usage logged as trimmings
  leftoverRate?: number; // share of cooked usage logged as over-bought leftovers
};

const ITEMS: Spec[] = [
  { name: "Chicken", unit: "kg", category: "meat", unitCost: 11, shelfLifeDays: 4, baseDaily: 1.2, orderEveryDays: 3, overOrder: 1.25, packSize: 1, trimRate: 0.03 },
  { name: "Eggs", unit: "pcs", category: "dairy", unitCost: 0.45, shelfLifeDays: 21, baseDaily: 30, orderEveryDays: 7, overOrder: 1.0, packSize: 30, kgPerUnit: 0.06 },
  { name: "Tomatoes", unit: "kg", category: "produce", unitCost: 6.5, shelfLifeDays: 6, baseDaily: 0.4, orderEveryDays: 7, overOrder: 1.25, packSize: 0.5, trimRate: 0.04 },
  { name: "Kangkung", unit: "kg", category: "produce", unitCost: 5, shelfLifeDays: 3, baseDaily: 0.6, orderEveryDays: 3, overOrder: 1.2, packSize: 0.5, trimRate: 0.06 },
  { name: "Sawi", unit: "kg", category: "produce", unitCost: 5.5, shelfLifeDays: 4, baseDaily: 0.5, orderEveryDays: 3, overOrder: 1.2, packSize: 0.5, trimRate: 0.05 },
  { name: "Bean sprouts", unit: "kg", category: "produce", unitCost: 4, shelfLifeDays: 2, baseDaily: 0.7, orderEveryDays: 2, overOrder: 1.2, packSize: 0.5, trimRate: 0.03 },
  { name: "Tofu", unit: "pcs", category: "chilled", unitCost: 1.2, shelfLifeDays: 4, baseDaily: 6, orderEveryDays: 3, overOrder: 1.2, packSize: 5, kgPerUnit: 0.3 },
  { name: "White bread", unit: "loaf", category: "bakery", unitCost: 3.8, shelfLifeDays: 4, baseDaily: 3, orderEveryDays: 2, overOrder: 1.2, packSize: 1, kgPerUnit: 0.6 },
  { name: "Fresh milk", unit: "L", category: "dairy", unitCost: 7.5, shelfLifeDays: 7, baseDaily: 0.8, orderEveryDays: 7, overOrder: 1.2, packSize: 1, kgPerUnit: 1.03 },
  { name: "Condensed milk", unit: "can", category: "dry", unitCost: 4.2, shelfLifeDays: 180, baseDaily: 1.5, orderEveryDays: 7, overOrder: 1.0, packSize: 12, kgPerUnit: 0.5 },
  { name: "Rice", unit: "kg", category: "dry", unitCost: 3.2, shelfLifeDays: 365, baseDaily: 5, orderEveryDays: 7, overOrder: 1.0, packSize: 10, leftoverRate: 0.03 },
  { name: "Yellow noodles", unit: "kg", category: "chilled", unitCost: 4.5, shelfLifeDays: 5, baseDaily: 1.1, orderEveryDays: 3, overOrder: 1.2, packSize: 0.5, leftoverRate: 0.025 },
  { name: "Kuey teow", unit: "kg", category: "chilled", unitCost: 4, shelfLifeDays: 3, baseDaily: 1.2, orderEveryDays: 3, overOrder: 1.2, packSize: 0.5 },
  { name: "Fish cake", unit: "kg", category: "seafood", unitCost: 14, shelfLifeDays: 7, baseDaily: 0.35, orderEveryDays: 7, overOrder: 1.2, packSize: 0.5 },
  { name: "Prawns", unit: "kg", category: "seafood", unitCost: 32, shelfLifeDays: 3, baseDaily: 0.25, orderEveryDays: 3, overOrder: 1.2, packSize: 0.25, trimRate: 0.04 },
  { name: "Kaya", unit: "kg", category: "dry", unitCost: 18, shelfLifeDays: 14, baseDaily: 0.2, orderEveryDays: 7, overOrder: 1.2, packSize: 0.5 },
];

const SPOILS = new Set(["produce", "meat", "seafood"]); // goes "off" rather than "expired"

export type SampleLot = {
  qty: number;
  remaining: number; // left at the end of the simulated history
  unitCost: number;
  purchasedAt: string;
  expiresAt: string;
  trail: number[]; // qty left at the end of each day from purchasedAt until expiry (or the last day)
  leftAtExpiry?: number; // qty left at the end of its expiry day (thrown away); unset if not expired yet
};

export type SampleItem = {
  id: number; // 1-based position, stands in for the database id
  name: string;
  unit: string;
  category: string;
  unitCost: number;
  shelfLifeDays: number;
  orderEveryDays: number;
  packSize: number;
  kgPerUnit: number;
  usualOrder: number;
  deliveryDays: string[];
  lots: SampleLot[];
  usages: { day: string; qty: number }[]; // what was actually used (sold), rounded as stored
  demand: Record<string, number>; // TRUE demand per day, before any run-out
};

export type SampleWaste = {
  itemId: number;
  qty: number;
  costRM: number;
  reason: Reason;
  day: string;
  kg: number;
  loggedAt: Date;
  pickup: number | null; // index into pickups
};

export type SamplePickup = {
  batchCode: string;
  partnerFarm: string;
  scheduledFor: Date;
  status: "COLLECTED";
  totalKg: number;
  returnType: "CREDIT" | "FRASS";
  collectedAt: Date;
  createdAt: Date;
};

export type SampleData = {
  today: string;
  from: string;
  to: string;
  items: SampleItem[];
  waste: SampleWaste[];
  pickups: SamplePickup[];
};

export type SampleOptions = {
  today?: string;
  /** Scales every item's over-ordering habit: 1 = default (~20% on perishables), 0.5 = ~10%, 1.5 = ~30%. */
  overOrderScale?: number;
};

export type ImportSummary = {
  items: number;
  sales: number;
  purchases: number;
  wasteLogs: number;
  pickups: number;
  from: string;
  to: string;
};

/** Simulate the 90 days in memory. Deterministic for a given today and options. */
export function generateSampleData({ today = todayKey(), overOrderScale = 1 }: SampleOptions = {}): SampleData {
  const rand = mulberry32(42);
  const between = (a: number, b: number) => a + rand() * (b - a);
  // Day-to-day demand noise: lognormal with ~25% spread (mean 1), typical for
  // a single item at a small outlet.
  const noise = (sigma = 0.25) => {
    const z = Math.sqrt(-2 * Math.log(1 - rand())) * Math.cos(2 * Math.PI * rand());
    return Math.exp(sigma * z - (sigma * sigma) / 2);
  };
  const r2 = (n: number) => Math.round(n * 100) / 100;

  const start = addDays(today, -SAMPLE_DAYS);
  const items: SampleItem[] = [];
  const allWaste: Omit<SampleWaste, "loggedAt" | "pickup">[] = [];

  ITEMS.forEach((spec, index) => {
    const overOrder = 1 + (spec.overOrder - 1) * overOrderScale;
    const need = spec.baseDaily * DOW_MEAN * spec.orderEveryDays * overOrder;
    const usualOrder = Math.max(spec.packSize, Math.round(need / spec.packSize) * spec.packSize);
    const kgPer = spec.kgPerUnit ?? 1;
    const item: SampleItem = {
      id: index + 1,
      name: spec.name,
      unit: spec.unit,
      category: spec.category,
      unitCost: spec.unitCost,
      shelfLifeDays: spec.shelfLifeDays,
      orderEveryDays: spec.orderEveryDays,
      packSize: spec.packSize,
      kgPerUnit: kgPer,
      usualOrder,
      deliveryDays: [],
      lots: [],
      usages: [],
      demand: {},
    };
    const lots = item.lots;
    const logWaste = (qty: number, unitCost: number, reason: Reason, day: string) => {
      if (qty < 0.05) return;
      allWaste.push({ itemId: item.id, qty: r2(qty), costRM: r2(qty * unitCost), reason, day, kg: qty * kgPer });
    };
    let trimAcc = 0;
    const offset = Math.floor(rand() * spec.orderEveryDays);

    for (let i = 0; i < SAMPLE_DAYS; i++) {
      const day = addDays(start, i);

      if ((i + offset) % spec.orderEveryDays === 0 || i === 0) {
        const unitCost = r2(spec.unitCost * between(0.95, 1.05));
        lots.push({ qty: usualOrder, remaining: usualOrder, unitCost, purchasedAt: day, expiresAt: addDays(day, spec.shelfLifeDays), trail: [] });
        item.deliveryDays.push(day);
      }

      // Usage, first-expiry-first-out.
      let demand = spec.baseDaily * DOW[dayOfWeek(day)] * demandMultiplier(day) * noise();
      item.demand[day] = demand;
      let used = 0;
      for (const lot of lots.filter((l) => l.remaining > 0 && l.expiresAt >= day).sort((a, b) => a.expiresAt.localeCompare(b.expiresAt))) {
        const take = Math.min(lot.remaining, demand);
        lot.remaining -= take;
        demand -= take;
        used += take;
        if (demand <= 0) break;
      }
      item.usages.push({ day, qty: r2(used) });

      // Occasional spoilage of perishables (fridge issues, bruising, etc.).
      if (spec.shelfLifeDays <= 7 && rand() < 0.015) {
        const lot = lots.find((l) => l.remaining > 0);
        if (lot) {
          const lost = lot.remaining * between(0.15, 0.35);
          lot.remaining -= lost;
          logWaste(lost, lot.unitCost, "SPOILED", day);
        } else rand(); // keep the random stream aligned when the shelf is empty
      }

      if (spec.trimRate) {
        trimAcc += used * spec.trimRate;
        if (i % 2 === 1) {
          logWaste(trimAcc, spec.unitCost, "TRIMMINGS", day);
          trimAcc = 0;
        }
      }
      if (spec.leftoverRate) logWaste(used * spec.leftoverRate * between(0.6, 1.4), spec.unitCost, "OVERBOUGHT", day);

      // Anything left at the end of its expiry day is thrown away.
      for (const lot of lots) {
        if (lot.expiresAt === day) {
          lot.leftAtExpiry = lot.remaining;
          if (lot.remaining > 0) logWaste(lot.remaining, lot.unitCost, SPOILS.has(spec.category) ? "SPOILED" : "EXPIRED", day);
          lot.remaining = 0;
        }
        if (lot.expiresAt >= day) lot.trail.push(lot.remaining);
      }
    }
    items.push(item);
  });

  // Group BSF-eligible waste into collected pickup batches whenever the
  // threshold was reached; whatever accumulated since the last one stays open.
  allWaste.sort((a, b) => a.day.localeCompare(b.day));
  const pickups: SamplePickup[] = [];
  const pickupOf = new Map<(typeof allWaste)[number], number>();
  let pending: typeof allWaste = [];
  let pendingKg = 0;
  for (const w of allWaste) {
    if (!isBsfEligible(w.reason)) continue;
    pending.push(w);
    pendingKg += w.kg;
    const collectedDay = addDays(w.day, 2);
    if (pendingKg >= BSF_PICKUP_THRESHOLD_KG && collectedDay < today) {
      const seq = pickups.length + 1;
      pickups.push({
        batchCode: `BSF-${w.day.replaceAll("-", "").slice(2)}-${String(seq).padStart(3, "0")}`,
        partnerFarm: BSF_PARTNER_FARM,
        scheduledFor: parseDay(addDays(w.day, 1)),
        status: "COLLECTED",
        totalKg: r2(pendingKg),
        returnType: seq % 3 === 0 ? "CREDIT" : "FRASS",
        collectedAt: parseDay(collectedDay),
        createdAt: parseDay(w.day),
      });
      for (const p of pending) pickupOf.set(p, pickups.length - 1);
      pending = [];
      pendingKg = 0;
    }
  }

  const waste = allWaste.map((w) => {
    const loggedAt = parseDay(w.day);
    loggedAt.setHours(15 + Math.floor(rand() * 7), Math.floor(rand() * 60));
    return { ...w, loggedAt, pickup: pickupOf.get(w) ?? null };
  });

  return { today, from: start, to: addDays(today, -1), items, waste, pickups };
}

export async function clearAllData(prisma: PrismaClient) {
  await prisma.wasteLog.deleteMany();
  await prisma.pickup.deleteMany();
  await prisma.usage.deleteMany();
  await prisma.purchase.deleteMany();
  await prisma.item.deleteMany();
}

export async function importSampleData(prisma: PrismaClient): Promise<ImportSummary> {
  const data = generateSampleData();
  await clearAllData(prisma);

  const itemIds = new Map<number, number>();
  for (const s of data.items) {
    const item = await prisma.item.create({
      data: {
        name: s.name,
        unit: s.unit,
        category: s.category,
        unitCost: s.unitCost,
        shelfLifeDays: s.shelfLifeDays,
        orderEveryDays: s.orderEveryDays,
        packSize: s.packSize,
        usualOrder: s.usualOrder,
        kgPerUnit: s.kgPerUnit,
      },
    });
    itemIds.set(s.id, item.id);
    await prisma.purchase.createMany({
      data: s.lots.map((l) => ({
        itemId: item.id,
        qty: l.qty,
        remaining: Math.round(l.remaining * 100) / 100,
        unitCost: l.unitCost,
        purchasedAt: parseDay(l.purchasedAt),
        expiresAt: parseDay(l.expiresAt),
      })),
    });
    await prisma.usage.createMany({ data: s.usages.map((u) => ({ itemId: item.id, qty: u.qty, date: parseDay(u.day) })) });
  }

  const pickupIds: number[] = [];
  for (const p of data.pickups) pickupIds.push((await prisma.pickup.create({ data: p })).id);

  await prisma.wasteLog.createMany({
    data: data.waste.map((w) => ({
      itemId: itemIds.get(w.itemId)!,
      qty: w.qty,
      costRM: w.costRM,
      reason: w.reason,
      loggedAt: w.loggedAt,
      bsfEligible: isBsfEligible(w.reason),
      pickupId: w.pickup === null ? null : pickupIds[w.pickup],
    })),
  });

  return {
    items: data.items.length,
    sales: data.items.reduce((a, i) => a + i.usages.length, 0),
    purchases: data.items.reduce((a, i) => a + i.lots.length, 0),
    wasteLogs: data.waste.length,
    pickups: data.pickups.length,
    from: data.from,
    to: data.to,
  };
}
